// lib/crmHelper.js
// 🔍 CRM Helper — Extract RAW payload dari WhatsApp message
// Fokus: ambil payload 100% mentah, sebelum dinormalisasi WA/serializer

import fs from 'fs/promises';
import path from 'path';

// ============================================================
// EXTRACT RAW QUOTED — ambil quotedMessage mentah dari message
// ============================================================

/**
 * Cari raw quotedMessage dari berbagai tipe message
 * Tidak pakai serializer — ambil langsung dari protokol WA
 *
 * @param {Object} message - Raw message dari Baileys
 * @returns {Object|null} - { quoted, type, source } atau null
 */
export function extractRawQuoted(message) {
    if (!message?.message) return null;

    const content = message.message;

    // Cek semua tipe message, cari yang punya contextInfo
    for (const [type, value] of Object.entries(content)) {
        if (!value || typeof value !== 'object') continue;

        // Direct contextInfo
        if (value.contextInfo?.quotedMessage) {
            return {
                quoted: value.contextInfo.quotedMessage,
                contextInfo: value.contextInfo,
                source: type,
                quoteType: 'direct'
            };
        }

        // messageContextInfo (jarang, tapi kadang ada)
        if (value.messageContextInfo?.quotedMessage) {
            return {
                quoted: value.messageContextInfo.quotedMessage,
                contextInfo: value.messageContextInfo,
                source: type,
                quoteType: 'messageContextInfo'
            };
        }
    }

    return null;
}

// ============================================================
// EXTRACT RAW MESSAGE — ambil payload mentah dari message
// ============================================================

/**
 * Ambil payload MENTAH dari message (self, bukan quoted)
 *
 * @param {Object} message - Raw message dari Baileys
 * @returns {Object|null} - { payload, type } atau null
 */
export function extractRawMessage(message) {
    if (!message?.message) return null;

    const content = message.message;

    // Ambil wrapper utama (biasanya yang pertama)
    const keys = Object.keys(content);
    if (keys.length === 0) return null;

    return {
        payload: content,
        type: keys[0],
        keys
    };
}

// ============================================================
// EXTRACT FULL RAW — extract seluruh payload pesan
// ============================================================

/**
 * Extract full raw payload dari message + quoted
 *
 * @param {Object} message - Raw message dari Baileys
 * @returns {Object}
 */
export function extractFullRaw(message) {
    const result = {
        key: message.key,
        pushName: message.pushName,
        messageTimestamp: message.messageTimestamp,
        message: message.message,
        quoted: null
    };

    const quotedData = extractRawQuoted(message);
    if (quotedData) {
        result.quoted = {
            quotedMessage: quotedData.quoted,
            contextInfo: quotedData.contextInfo,
            source: quotedData.source,
            quoteType: quotedData.quoteType
        };
    }

    return result;
}

// ============================================================
// GENERATE JS FILE — bikin file .js dari raw payload
// ============================================================

/**
 * Generate file .js dari raw payload
 *
 * @param {Object} data - Data yang mau di-extract
 * @param {Object} options
 * @returns {Object} - { content, fileName, metadata }
 */
export function generateRawJSFile(data, options = {}) {
    const {
        name = 'payload',
        mode = 'quoted',  // 'quoted' | 'full' | 'message'
        metadata = {}
    } = options;

    let payload;
    let type;
    let source;

    if (mode === 'quoted') {
        if (!data.quoted) throw new Error('No quoted data');
        payload = data.quoted.quotedMessage;
        type = Object.keys(payload)[0] || 'unknown';
        source = data.quoted.source;
    } else if (mode === 'full') {
        payload = {
            key: data.key,
            pushName: data.pushName,
            message: data.message,
            quoted: data.quoted?.quotedMessage || null
        };
        type = 'full';
        source = 'full';
    } else if (mode === 'message') {
        if (!data.message) throw new Error('No message data');
        payload = data.message;
        type = Object.keys(payload)[0] || 'unknown';
        source = 'message';
    } else {
        throw new Error(`Unknown mode: ${mode}`);
    }

    const timestamp = new Date().toISOString();

    const content = `// Raw Message Payload — extracted by .crm
// Generated by FarrMdV2 CRM Helper
// Date: ${timestamp}
// Mode: ${mode}
// Source: ${source}
// Type: ${type}
${Object.entries(metadata).map(([k, v]) => `// ${k}: ${v}`).join('\n')}

export default ${JSON.stringify(payload, null, 4)};
`;

    const fileName = `${name}_${type}.js`;

    return {
        content,
        fileName,
        metadata: {
            type,
            source,
            mode,
            size: content.length,
            ...metadata
        }
    };
}

// ============================================================
// ANALYSIS — analisa struktur payload
// ============================================================

/**
 * Analisa struktur raw payload untuk ringkasan
 *
 * @param {Object} payload - Raw payload
 * @returns {Object} - { type, keys, hasContextInfo, children, summary }
 */
export function analyzePayload(payload) {
    if (!payload || typeof payload !== 'object') {
        return { error: 'Invalid payload' };
    }

    const keys = Object.keys(payload);
    const type = keys[0] || 'unknown';
    const primary = payload[type];

    const result = {
        type,
        keys,
        children: keys.length,
        hasContextInfo: false,
        hasQuoted: false,
        hasMedia: false,
        contextInfo: null
    };

    if (primary && typeof primary === 'object') {
        if (primary.contextInfo) {
            result.hasContextInfo = true;
            result.contextInfo = primary.contextInfo;

            if (primary.contextInfo.quotedMessage) {
                result.hasQuoted = true;
            }
        }

        // Cek media
        if (primary.mimetype || primary.fileName || primary.mediaKey) {
            result.hasMedia = true;
        }
    }

    return result;
}

// ============================================================
// CONSTRUCT SUMMARY — bikin ringkasan text
// ============================================================

/**
 * Bikin caption text dari analisa payload
 *
 * @param {Object} analysis - Hasil analyzePayload
 * @param {Object} message - Raw message
 * @returns {String}
 */
export function constructCaption(analysis, message) {
    const key = message?.key || {};

    const lines = [
        '✅ *Raw code extracted*',
        '',
        `• *Type:* ${analysis.type}`,
        `• *Source:* ${analysis.source || 'quote'}`,
        `• *Chat:* ${key.remoteJid || '-'}`,
        `• *ID:* ${key.id || '-'}`,
        `• *Sender:* ${key.participant || key.remoteJid || '-'}`,
        `• *Children:* ${analysis.children || 0}`
    ];

    if (analysis.hasContextInfo) lines.push('• *Has ContextInfo:* ✅');
    if (analysis.hasQuoted) lines.push('• *Has Quoted:* ✅');
    if (analysis.hasMedia) lines.push('• *Has Media:* ✅');

    return lines.join('\n');
}

// ============================================================
// EXPORT DEFAULT
// ============================================================

export default {
    extractRawQuoted,
    extractRawMessage,
    extractFullRaw,
    generateRawJSFile,
    analyzePayload,
    constructCaption
};